# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3 p4 p5

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe p5.exe
	rm -f p1 p2 p3 p4 p5

p1: StringyProg_1.cpp

	$(CC) $(CXX) -o p1 "$^"

p2: StringyProg_2.cpp

	$(CC) $(CXX) -o p2 "$^"

p3: StringyProg_3.cpp

	$(CC) $(CXX) -o p3 "$^"

p4: StringyProg_4.cpp

	$(CC) $(CXX) -o p4 "$^"

p5: StringyProg_5.cpp

	$(CC) $(CXX) -o p5 "$^"
