# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3 p4 p5

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe p5.exe
	rm -f p1 p2 p3 p4 p5

p1: ClassyProg_1.cpp

	$(CC) $(CXX) -o p1 "$^"

p2: ClassyProg_2.cpp

	$(CC) $(CXX) -o p2 "$^"

p3: ClassyProg_3.cpp

	$(CC) $(CXX) -o p3 "$^"

p4: ClassyProg_4.cpp

	$(CC) $(CXX) -o p4 "$^"

p5: ClassyProg_5.cpp

	$(CC) $(CXX) -o p5 "$^"