# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3

clean:

	rm -f p1.exe p2.exe p3.exe
	rm -f p1 p2 p3

p1: Ptrogram_1.cpp

	$(CC) $(CXX) -o p1 "$^"

p2: Ptrogram_2.cpp

	$(CC) $(CXX) -o p2 "$^"

p3: Ptrogram_3.cpp

	$(CC) $(CXX) -o p3 "$^"
