# -*- Makefile -*-

CC = g++
CXX = -Wall

all: p1 p2 p3 p4

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe
	rm -f p1 p2 p3 p4

p1: Superset_1_Sub_A.cpp

	$(CC) $(CXX) -o p1 "Superset_1_Sub_A.cpp"

p2: Superset_1_Sub_B.cpp

	$(CC) $(CXX) -o p2 "Superset_1_Sub_B.cpp"

p3: Superset_1_Sub_C.cpp

	$(CC) $(CXX) -o p3 "Superset_1_Sub_C.cpp"

p4: Superset_1_Sub_D.cpp

	$(CC) $(CXX) -o p4 "Superset_1_Sub_D.cpp"