# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3 p4 p5

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe p5.exe
	rm -f p1 p2 p3 p4 p5

p1: ManipProg_1.cpp

	$(CC) $(CXX) -o p1 "ManipProg_1.cpp"

p2: ManipProg_2.cpp

	$(CC) $(CXX) -o p2 "ManipProg_2.cpp"

p3: ManipProg_3.cpp

	$(CC) $(CXX) -o p3 "ManipProg_3.cpp"

p4: ManipProg_4.cpp

	$(CC) $(CXX) -o p4 "ManipProg_4.cpp"

p5: ManipProg_5.cpp

	$(CC) $(CXX) -o p5 "ManipProg_5.cpp"