# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3 p4

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe
	rm -f p1 p2 p3 p4

p1: HeritProg_1.cpp

	$(CC) $(CXX) -o p1 "$^"

p2: HeritProg_2.cpp

	$(CC) $(CXX) -o p2 "$^"

p3: HeritProg_3.cpp

	$(CC) $(CXX) -o p3 "$^"

p4: HeritProg_4.cpp

	$(CC) $(CXX) -o p4 "$^"
