# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3 p4 p5

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe p5.exe
	rm -f p1 p2 p3 p4 p5

p1: FunProg_1.cpp

	$(CC) $(CXX) -o p1 "$^"

p2: FunProg_2.cpp

	$(CC) $(CXX) -o p2 "$^"

p3: FunProg_3.cpp

	$(CC) $(CXX) -o p3 "$^"

p4: FunProg_4.cpp

	$(CC) $(CXX) -o p4 "$^"

p5: FunProg_5.cpp

	$(CC) $(CXX) -o p5 "$^"