# -*- Makefile -*-

CC = clang++
CXX = -Wall

all: p1 p2 p3 p4 p5 p6

clean:

	rm -f p1.exe p2.exe p3.exe p4.exe p5.exe p6.exe
	rm -f p1 p2 p3 p4 p5 p6

p1: OProg_1.cpp

	$(CC) $(CXX) -o p1 "$^"

p2: OProg_2.cpp

	$(CC) $(CXX) -o p2 "$^"

p3: OProg_3.cpp

	$(CC) $(CXX) -o p3 "$^"

p4: OProg_4.cpp

	$(CC) $(CXX) -o p4 "$^"

p5: OProg_5.cpp

	$(CC) $(CXX) -o p5 "$^"

p6: OProg_6.cpp

	$(CC) $(CXX) -o p6 "$^"
